"""Entity descriptions for the derived values, generated.

Do not edit by hand: `scripts/generate_derived.py` writes this file, and CI
checks it. The arithmetic itself lives in `sungrow_modbus.derived`.

Each entry names the registers its value reads, which decides both the
coordinator that writes it — the fastest tier among them, so a derived value
never lags the sensors it is computed from — and when it is unavailable.
"""

from __future__ import annotations

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import EntityCategory
from sungrow_modbus import Capability

from .entity import SungrowBinarySensorDescription, SungrowSensorDescription

DERIVED_SENSORS: tuple[SungrowSensorDescription, ...] = (
    SungrowSensorDescription(
        key="mppt1_power",
        component="derived",
        field="mppt1_power",
        translation_key="mppt1_power",
        legacy_name="MPPT1 power",
        depends_on=("mppt1_voltage", "mppt1_current"),
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="mppt2_power",
        component="derived",
        field="mppt2_power",
        translation_key="mppt2_power",
        legacy_name="MPPT2 power",
        depends_on=("mppt2_voltage", "mppt2_current"),
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="mppt3_power",
        component="derived",
        field="mppt3_power",
        translation_key="mppt3_power",
        legacy_name="MPPT3 power",
        depends_on=("mppt3_voltage", "mppt3_current"),
        requires=Capability.MPPT3,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="mppt4_power",
        component="derived",
        field="mppt4_power",
        translation_key="mppt4_power",
        legacy_name="MPPT4 power",
        depends_on=("mppt4_voltage", "mppt4_current"),
        requires=Capability.MPPT4,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="phase_a_power",
        component="derived",
        field="phase_a_power",
        translation_key="phase_a_power",
        legacy_name="Phase A power",
        depends_on=("phase_a_voltage", "phase_a_current"),
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="phase_b_power",
        component="derived",
        field="phase_b_power",
        translation_key="phase_b_power",
        legacy_name="Phase B power",
        depends_on=("phase_b_voltage", "phase_b_current"),
        requires=Capability.THREE_PHASE,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="phase_c_power",
        component="derived",
        field="phase_c_power",
        translation_key="phase_c_power",
        legacy_name="Phase C power",
        depends_on=("phase_c_voltage", "phase_c_current"),
        requires=Capability.THREE_PHASE,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="sungrow_inverter_state",
        component="derived",
        field="inverter_state",
        translation_key="sungrow_inverter_state",
        legacy_name="Sungrow inverter state",
        depends_on=("running_state_raw",),
        device_class=SensorDeviceClass.ENUM,
    ),
    SungrowSensorDescription(
        key="sungrow_device_type",
        component="derived",
        field="sungrow_device_type",
        translation_key="sungrow_device_type",
        legacy_name="Sungrow device type",
        depends_on=("sungrow_device_type_code",),
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.ENUM,
    ),
    SungrowSensorDescription(
        key="battery_charging_power_signed",
        component="derived",
        field="battery_charging_power_signed",
        translation_key="battery_charging_power_signed",
        legacy_name="Battery charging power signed",
        depends_on=("battery_power",),
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="battery_charging_power",
        component="derived",
        field="battery_charging_power",
        translation_key="battery_charging_power",
        legacy_name="Battery charging power",
        depends_on=("battery_power",),
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="battery_discharging_power_signed",
        component="derived",
        field="battery_discharging_power_signed",
        translation_key="battery_discharging_power_signed",
        legacy_name="Battery discharging power signed",
        depends_on=("battery_power",),
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="battery_discharging_power",
        component="derived",
        field="battery_discharging_power",
        translation_key="battery_discharging_power",
        legacy_name="Battery discharging power",
        depends_on=("battery_power",),
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="export_power",
        component="derived",
        field="export_power",
        translation_key="export_power",
        legacy_name="Export power",
        depends_on=("export_power_raw",),
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="import_power",
        component="derived",
        field="import_power",
        translation_key="import_power",
        legacy_name="Import power",
        depends_on=("export_power_raw",),
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="battery_level_nominal",
        component="derived",
        field="battery_level_nominal",
        translation_key="battery_level_nominal",
        legacy_name="Battery level (nominal)",
        depends_on=("battery_min_soc", "battery_max_soc", "battery_level"),
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
    ),
    SungrowSensorDescription(
        key="battery_charge_nominal",
        component="derived",
        field="battery_charge_nominal",
        translation_key="battery_charge_nominal",
        legacy_name="Battery charge (nominal)",
        depends_on=(
            "battery_min_soc",
            "battery_max_soc",
            "battery_level",
            "battery_capacity_high_precision",
        ),
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="kWh",
    ),
    SungrowSensorDescription(
        key="battery_charge",
        component="derived",
        field="battery_charge",
        translation_key="battery_charge",
        legacy_name="Battery charge",
        depends_on=(
            "battery_min_soc",
            "battery_max_soc",
            "battery_capacity_high_precision",
        ),
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="kWh",
    ),
    SungrowSensorDescription(
        key="battery_charge_health_rated",
        component="derived",
        field="battery_charge_health_rated",
        translation_key="battery_charge_health_rated",
        legacy_name="Battery charge (health-rated)",
        depends_on=(
            "battery_min_soc",
            "battery_max_soc",
            "battery_capacity_high_precision",
            "battery_state_of_health",
        ),
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="kWh",
    ),
    SungrowSensorDescription(
        key="daily_consumed_energy",
        component="derived",
        field="daily_consumed_energy",
        translation_key="daily_consumed_energy",
        legacy_name="Daily consumed energy",
        depends_on=(
            "daily_pv_generation",
            "daily_exported_energy",
            "daily_imported_energy",
            "daily_battery_charge",
            "daily_battery_discharge",
        ),
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        native_unit_of_measurement="kWh",
    ),
    SungrowSensorDescription(
        key="total_consumed_energy",
        component="derived",
        field="total_consumed_energy",
        translation_key="total_consumed_energy",
        legacy_name="Total consumed energy",
        depends_on=(
            "total_pv_generation",
            "total_exported_energy",
            "total_imported_energy",
            "total_battery_charge",
            "total_battery_discharge",
        ),
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        native_unit_of_measurement="kWh",
    ),
)

DERIVED_BINARY_SENSORS: tuple[SungrowBinarySensorDescription, ...] = (
    SungrowBinarySensorDescription(
        key="pv_generating",
        component="derived",
        field="pv_generating",
        translation_key="pv_generating",
        legacy_name="PV generating",
        depends_on=("power_flow_status",),
    ),
    SungrowBinarySensorDescription(
        key="battery_charging",
        component="derived",
        field="battery_charging",
        translation_key="battery_charging",
        legacy_name="Battery charging",
        depends_on=("power_flow_status",),
    ),
    SungrowBinarySensorDescription(
        key="battery_discharging",
        component="derived",
        field="battery_discharging",
        translation_key="battery_discharging",
        legacy_name="Battery discharging",
        depends_on=("power_flow_status",),
    ),
    SungrowBinarySensorDescription(
        key="positive_load_power",
        component="derived",
        field="positive_load_power",
        translation_key="positive_load_power",
        legacy_name="Positive Load Power",
        depends_on=("power_flow_status",),
    ),
    SungrowBinarySensorDescription(
        key="exporting_power",
        component="derived",
        field="exporting_power",
        translation_key="exporting_power",
        legacy_name="Exporting Power",
        depends_on=("power_flow_status",),
    ),
    SungrowBinarySensorDescription(
        key="importing_power",
        component="derived",
        field="importing_power",
        translation_key="importing_power",
        legacy_name="Importing Power",
        depends_on=("power_flow_status",),
    ),
    SungrowBinarySensorDescription(
        key="negative_load_power",
        component="derived",
        field="negative_load_power",
        translation_key="negative_load_power",
        legacy_name="Negative Load Power",
        depends_on=("power_flow_status",),
    ),
)
