"""Number descriptions, generated from the write table.

Do not edit by hand: `scripts/generate_numbers.py` writes this file from
`scripts/writes.py`, and CI checks that it matches.

Each of these reads and writes one register. The YAML package needed three
pieces for that — a `template number`, a `modbus.write_register` action and a
`homeassistant.update_entity` call to see the result — because YAML Modbus has
no write-then-read. An integration does not.
"""

from __future__ import annotations

from homeassistant.components.number import NumberDeviceClass, NumberMode
from homeassistant.const import PERCENTAGE, EntityCategory, UnitOfPower
from sungrow_modbus import Capability

from .entity import SungrowNumberDescription

NUMBER_DESCRIPTIONS: tuple[SungrowNumberDescription, ...] = (
    SungrowNumberDescription(
        key="battery_min_soc",
        component="fast_holding",
        field="battery_min_soc",
        translation_key="battery_min_soc",
        legacy_name="Battery Min Soc",
        legacy_unique_id="uid_battery_min_soc",
        legacy_platform="template",
        requires=Capability.BATTERY,
        native_min_value=0,
        native_max_value=50,
        native_step=1,
        native_unit_of_measurement=PERCENTAGE,
        device_class=NumberDeviceClass.BATTERY,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
    ),
    SungrowNumberDescription(
        key="battery_max_soc",
        component="fast_holding",
        field="battery_max_soc",
        translation_key="battery_max_soc",
        legacy_name="Battery Max Soc",
        legacy_unique_id="uid_battery_max_soc",
        legacy_platform="template",
        requires=Capability.BATTERY,
        native_min_value=50,
        native_max_value=100,
        native_step=1,
        native_unit_of_measurement=PERCENTAGE,
        device_class=NumberDeviceClass.BATTERY,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
    ),
    SungrowNumberDescription(
        key="battery_reserved_soc_for_backup",
        component="fast_holding",
        field="battery_reserved_soc_for_backup",
        translation_key="battery_reserved_soc_for_backup",
        legacy_name="Battery Reserved SoC for Backup",
        legacy_unique_id="uid_battery_reserved_soc_for_backup",
        legacy_platform="template",
        requires=Capability.BATTERY,
        native_min_value=0,
        native_max_value=100,
        native_step=1,
        native_unit_of_measurement=PERCENTAGE,
        device_class=NumberDeviceClass.BATTERY,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
    ),
    SungrowNumberDescription(
        key="battery_max_charge_power",
        component="fast_holding",
        field="battery_max_charge_power",
        translation_key="battery_max_charge_power",
        legacy_name="Battery max charge power",
        legacy_unique_id="uid_battery_max_charge_power",
        legacy_platform="template",
        requires=Capability.BATTERY,
        native_min_value=10,
        native_max_value=0,
        native_step=100,
        maximum_from_battery=True,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=NumberDeviceClass.POWER,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
    ),
    SungrowNumberDescription(
        key="battery_max_discharge_power",
        component="fast_holding",
        field="battery_max_discharge_power",
        translation_key="battery_max_discharge_power",
        legacy_name="Battery max discharge power",
        legacy_unique_id="uid_battery_max_discharge_power",
        legacy_platform="template",
        requires=Capability.BATTERY,
        native_min_value=10,
        native_max_value=0,
        native_step=100,
        maximum_from_battery=True,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=NumberDeviceClass.POWER,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
    ),
    SungrowNumberDescription(
        key="export_power_limit",
        component="fast_holding",
        field="export_power_limit",
        translation_key="export_power_limit",
        legacy_name="Export power limit",
        legacy_unique_id="uid_export_power_limit",
        legacy_platform="template",
        native_min_value=0,
        native_max_value=0,
        native_step=100,
        minimum_field="export_power_limit_min",
        maximum_field="export_power_limit_max",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=NumberDeviceClass.POWER,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
    ),
    SungrowNumberDescription(
        key="battery_forced_charge_discharge_power",
        component="fast_holding",
        field="battery_forced_charge_discharge_power",
        translation_key="battery_forced_charge_discharge_power",
        legacy_name="Battery forced charge discharge power",
        legacy_unique_id="uid_battery_forced_charge_discharge_power",
        legacy_platform="template",
        requires=Capability.BATTERY,
        native_min_value=0,
        native_max_value=0,
        native_step=100,
        maximum_from_battery=True,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=NumberDeviceClass.POWER,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
    ),
    SungrowNumberDescription(
        key="battery_charging_start_power",
        component="fast_holding",
        field="battery_charging_start_power",
        translation_key="battery_charging_start_power",
        legacy_name="Battery charging start power",
        legacy_unique_id="uid_battery_charging_start_power",
        legacy_platform="template",
        requires=Capability.BATTERY,
        native_min_value=0,
        native_max_value=1000,
        native_step=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=NumberDeviceClass.POWER,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
    ),
    SungrowNumberDescription(
        key="battery_discharging_start_power",
        component="fast_holding",
        field="battery_discharging_start_power",
        translation_key="battery_discharging_start_power",
        legacy_name="Battery discharging start power",
        legacy_unique_id="uid_battery_discharging_start_power",
        legacy_platform="template",
        requires=Capability.BATTERY,
        native_min_value=0,
        native_max_value=1000,
        native_step=10,
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=NumberDeviceClass.POWER,
        mode=NumberMode.BOX,
        entity_category=EntityCategory.CONFIG,
    ),
)
