"""Sensor descriptions, generated from the YAML package.

Do not edit by hand: `scripts/generate_sensors.py` writes this file from
`doc/legacy_entity_map.json`, and CI checks that it matches.

Every entry carries the unit and state class of the YAML entry it replaces,
because a replacement in a different unit class silently freezes long-term
statistics, and `legacy_name`, which is what legacy mode sets so the
entity_id comes out identical to the one a user already has. The modern name
is not here: it lives in `strings.json` under `translation_key`, so it can be
translated.
"""

from __future__ import annotations

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import EntityCategory
from sungrow_modbus import Capability

from .entity import SungrowSensorDescription

SENSOR_DESCRIPTIONS: tuple[SungrowSensorDescription, ...] = (
    SungrowSensorDescription(
        key="active_power_limitation_ratio_raw",
        component="fast_holding",
        field="active_power_limitation_ratio_raw",
        translation_key="active_power_limitation_ratio_raw",
        legacy_name="Active power limitation ratio raw",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
    ),
    SungrowSensorDescription(
        key="active_power_limitation_raw",
        component="fast_holding",
        field="active_power_limitation_raw",
        translation_key="active_power_limitation_raw",
        legacy_name="Active power limitation raw",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="apl_shutdown_at_zero_raw",
        component="fast_holding",
        field="apl_shutdown_at_zero_raw",
        translation_key="apl_shutdown_at_zero_raw",
        legacy_name="APL shutdown at zero raw",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="backup_mode_raw",
        component="fast_holding",
        field="backup_mode_raw",
        translation_key="backup_mode_raw",
        legacy_name="Backup mode raw",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="backup_phase_a_power",
        component="fast_input",
        field="backup_phase_a_power",
        translation_key="backup_phase_a_power",
        legacy_name="Backup phase A power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="backup_phase_b_power",
        component="fast_input",
        field="backup_phase_b_power",
        translation_key="backup_phase_b_power",
        legacy_name="Backup phase B power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="backup_phase_c_power",
        component="fast_input",
        field="backup_phase_c_power",
        translation_key="backup_phase_c_power",
        legacy_name="Backup phase C power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="battery_capacity_high_precision",
        component="slowest_input",
        field="battery_capacity_high_precision",
        translation_key="battery_capacity_high_precision",
        legacy_name="Battery capacity high precision",
        device_class=SensorDeviceClass.ENERGY_STORAGE,
        native_unit_of_measurement="kWh",
        suggested_display_precision=2,
    ),
    SungrowSensorDescription(
        key="battery_charging_start_power",
        component="fast_holding",
        field="battery_charging_start_power",
        translation_key="battery_charging_start_power",
        legacy_name="Battery charging start power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="battery_current",
        component="fast_input",
        field="battery_current",
        translation_key="battery_current",
        legacy_name="Battery current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="battery_discharging_start_power",
        component="fast_holding",
        field="battery_discharging_start_power",
        translation_key="battery_discharging_start_power",
        legacy_name="Battery discharging start power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="battery_firmware_version",
        component="slowest_input",
        field="battery_firmware_version",
        translation_key="battery_firmware_version",
        legacy_name="Battery Firmware Version",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SungrowSensorDescription(
        key="battery_forced_charge_discharge_cmd_raw",
        component="fast_holding",
        field="battery_forced_charge_discharge_cmd_raw",
        translation_key="battery_forced_charge_discharge_cmd_raw",
        legacy_name="Battery forced charge discharge cmd raw",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="battery_forced_charge_discharge_power",
        component="fast_holding",
        field="battery_forced_charge_discharge_power",
        translation_key="battery_forced_charge_discharge_power",
        legacy_name="Battery forced charge discharge power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="battery_level",
        component="medium_input",
        field="battery_level",
        translation_key="battery_level",
        legacy_name="Battery level",
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="battery_max_charge_power",
        component="fast_holding",
        field="battery_max_charge_power",
        translation_key="battery_max_charge_power",
        legacy_name="Battery max charge power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="battery_max_discharge_power",
        component="fast_holding",
        field="battery_max_discharge_power",
        translation_key="battery_max_discharge_power",
        legacy_name="Battery max discharge power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="battery_max_soc",
        component="fast_holding",
        field="battery_max_soc",
        translation_key="battery_max_soc",
        legacy_name="Battery max SoC",
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="battery_min_soc",
        component="fast_holding",
        field="battery_min_soc",
        translation_key="battery_min_soc",
        legacy_name="Battery min SoC",
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="battery_power",
        component="fast_input",
        field="battery_power",
        translation_key="battery_power",
        legacy_name="Battery power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="battery_reserved_soc_for_backup",
        component="fast_holding",
        field="battery_reserved_soc_for_backup",
        translation_key="battery_reserved_soc_for_backup",
        legacy_name="Battery reserved SoC for backup",
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
    ),
    SungrowSensorDescription(
        key="battery_state_of_health",
        component="slowest_input",
        field="battery_state_of_health",
        translation_key="battery_state_of_health",
        legacy_name="Battery state of health",
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="battery_temperature",
        component="medium_input",
        field="battery_temperature",
        translation_key="battery_temperature",
        legacy_name="Battery temperature",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="°C",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="battery_voltage",
        component="fast_input",
        field="battery_voltage",
        translation_key="battery_voltage",
        legacy_name="Battery voltage",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="bdc_rated_power",
        component="slowest_input",
        field="bdc_rated_power",
        translation_key="bdc_rated_power",
        legacy_name="BDC rated power",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="bms_max_charging_current",
        component="slowest_input",
        field="bms_max_charging_current",
        translation_key="bms_max_charging_current",
        legacy_name="BMS max. charging current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="bms_max_discharging_current",
        component="slowest_input",
        field="bms_max_discharging_current",
        translation_key="bms_max_discharging_current",
        legacy_name="BMS max. discharging current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="communication_module_firmware_version",
        component="slowest_input",
        field="communication_module_firmware_version",
        translation_key="communication_module_firmware_version",
        legacy_name="Communication Module Firmware Version",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SungrowSensorDescription(
        key="daily_battery_charge",
        component="slowest_input",
        field="daily_battery_charge",
        translation_key="daily_battery_charge",
        legacy_name="Daily battery charge",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_battery_charge_from_pv",
        component="slowest_input",
        field="daily_battery_charge_from_pv",
        translation_key="daily_battery_charge_from_pv",
        legacy_name="Daily battery charge from PV",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_battery_discharge",
        component="slowest_input",
        field="daily_battery_discharge",
        translation_key="daily_battery_discharge",
        legacy_name="Daily battery discharge",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_direct_energy_consumption",
        component="slowest_input",
        field="daily_direct_energy_consumption",
        translation_key="daily_direct_energy_consumption",
        legacy_name="Daily direct energy consumption",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_exported_energy",
        component="slowest_input",
        field="daily_exported_energy",
        translation_key="daily_exported_energy",
        legacy_name="Daily exported energy",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_exported_energy_from_pv",
        component="slowest_input",
        field="daily_exported_energy_from_pv",
        translation_key="daily_exported_energy_from_pv",
        legacy_name="Daily exported energy from PV",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_imported_energy",
        component="slowest_input",
        field="daily_imported_energy",
        translation_key="daily_imported_energy",
        legacy_name="Daily imported energy",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_pv_generation",
        component="slowest_input",
        field="daily_pv_generation",
        translation_key="daily_pv_generation",
        legacy_name="Daily PV generation",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="daily_pv_generation_battery_discharge",
        component="slowest_input",
        field="daily_pv_generation_battery_discharge",
        translation_key="daily_pv_generation_battery_discharge",
        legacy_name="Daily PV generation & battery discharge",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="ems_mode_selection_raw",
        component="fast_holding",
        field="ems_mode_selection_raw",
        translation_key="ems_mode_selection_raw",
        legacy_name="EMS mode selection raw",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="export_power_limit",
        component="fast_holding",
        field="export_power_limit",
        translation_key="export_power_limit",
        legacy_name="Export power limit",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="export_power_limit_max",
        component="slowest_input",
        field="export_power_limit_max",
        translation_key="export_power_limit_max",
        legacy_name="Export power limit max",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="export_power_limit_min",
        component="slowest_input",
        field="export_power_limit_min",
        translation_key="export_power_limit_min",
        legacy_name="Export power limit min",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="export_power_limit_mode_raw",
        component="fast_holding",
        field="export_power_limit_mode_raw",
        translation_key="export_power_limit_mode_raw",
        legacy_name="Export power limit mode raw",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="export_power_raw",
        component="fast_input",
        field="export_power_raw",
        translation_key="export_power_raw",
        legacy_name="Export power raw",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="grid_frequency",
        component="fast_input",
        field="grid_frequency",
        translation_key="grid_frequency",
        legacy_name="Grid frequency",
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="Hz",
        suggested_display_precision=2,
    ),
    SungrowSensorDescription(
        key="inverter_firmware_version",
        component="slowest_input",
        field="inverter_firmware_version",
        translation_key="inverter_firmware_version",
        legacy_name="Inverter Firmware Version",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SungrowSensorDescription(
        key="inverter_rated_output",
        component="slowest_input",
        field="inverter_rated_output",
        translation_key="inverter_rated_output",
        legacy_name="Inverter rated output",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
    ),
    SungrowSensorDescription(
        key="inverter_temperature",
        component="medium_input",
        field="inverter_temperature",
        translation_key="inverter_temperature",
        legacy_name="Inverter temperature",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="°C",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="load_adjustment_mode_enable_raw",
        component="fast_holding",
        field="load_adjustment_mode_enable_raw",
        translation_key="load_adjustment_mode_enable_raw",
        legacy_name="Load adjustment mode enable raw",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="load_adjustment_mode_selection_raw",
        component="fast_holding",
        field="load_adjustment_mode_selection_raw",
        translation_key="load_adjustment_mode_selection_raw",
        legacy_name="Load adjustment mode selection raw",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SungrowSensorDescription(
        key="load_power",
        component="realtime_input",
        field="load_power",
        translation_key="load_power",
        legacy_name="Load power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="meter_active_power",
        component="fast_input",
        field="meter_active_power",
        translation_key="meter_active_power",
        legacy_name="Meter active power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="meter_phase_a_active_power",
        component="fast_input",
        field="meter_phase_a_active_power",
        translation_key="meter_phase_a_active_power",
        legacy_name="Meter phase A active power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="meter_phase_a_current",
        component="fast_input",
        field="meter_phase_a_current",
        translation_key="meter_phase_a_current",
        legacy_name="Meter phase A current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=2,
    ),
    SungrowSensorDescription(
        key="meter_phase_a_voltage",
        component="fast_input",
        field="meter_phase_a_voltage",
        translation_key="meter_phase_a_voltage",
        legacy_name="Meter phase A voltage",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="meter_phase_b_active_power",
        component="fast_input",
        field="meter_phase_b_active_power",
        translation_key="meter_phase_b_active_power",
        legacy_name="Meter phase B active power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="meter_phase_b_current",
        component="fast_input",
        field="meter_phase_b_current",
        translation_key="meter_phase_b_current",
        legacy_name="Meter phase B current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=2,
    ),
    SungrowSensorDescription(
        key="meter_phase_b_voltage",
        component="fast_input",
        field="meter_phase_b_voltage",
        translation_key="meter_phase_b_voltage",
        legacy_name="Meter phase B voltage",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="meter_phase_c_active_power",
        component="fast_input",
        field="meter_phase_c_active_power",
        translation_key="meter_phase_c_active_power",
        legacy_name="Meter phase C active power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="meter_phase_c_current",
        component="fast_input",
        field="meter_phase_c_current",
        translation_key="meter_phase_c_current",
        legacy_name="Meter phase C current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=2,
    ),
    SungrowSensorDescription(
        key="meter_phase_c_voltage",
        component="fast_input",
        field="meter_phase_c_voltage",
        translation_key="meter_phase_c_voltage",
        legacy_name="Meter phase C voltage",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt1_current",
        component="fast_input",
        field="mppt1_current",
        translation_key="mppt1_current",
        legacy_name="MPPT1 current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt1_voltage",
        component="fast_input",
        field="mppt1_voltage",
        translation_key="mppt1_voltage",
        legacy_name="MPPT1 voltage",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt2_current",
        component="fast_input",
        field="mppt2_current",
        translation_key="mppt2_current",
        legacy_name="MPPT2 current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt2_voltage",
        component="fast_input",
        field="mppt2_voltage",
        translation_key="mppt2_voltage",
        legacy_name="MPPT2 voltage",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt3_current",
        component="fast_input",
        field="mppt3_current",
        translation_key="mppt3_current",
        legacy_name="MPPT3 current",
        requires=Capability.MPPT3,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt3_voltage",
        component="fast_input",
        field="mppt3_voltage",
        translation_key="mppt3_voltage",
        legacy_name="MPPT3 voltage",
        requires=Capability.MPPT3,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt4_current",
        component="fast_input",
        field="mppt4_current",
        translation_key="mppt4_current",
        legacy_name="MPPT4 current",
        requires=Capability.MPPT4,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="mppt4_voltage",
        component="fast_input",
        field="mppt4_voltage",
        translation_key="mppt4_voltage",
        legacy_name="MPPT4 voltage",
        requires=Capability.MPPT4,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="phase_a_current",
        component="fast_input",
        field="phase_a_current",
        translation_key="phase_a_current",
        legacy_name="Phase A current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="phase_a_voltage",
        component="fast_input",
        field="phase_a_voltage",
        translation_key="phase_a_voltage",
        legacy_name="Phase A voltage",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="phase_b_current",
        component="fast_input",
        field="phase_b_current",
        translation_key="phase_b_current",
        legacy_name="Phase B current",
        requires=Capability.THREE_PHASE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="phase_b_voltage",
        component="fast_input",
        field="phase_b_voltage",
        translation_key="phase_b_voltage",
        legacy_name="Phase B voltage",
        requires=Capability.THREE_PHASE,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="phase_c_current",
        component="fast_input",
        field="phase_c_current",
        translation_key="phase_c_current",
        legacy_name="Phase C current",
        requires=Capability.THREE_PHASE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="A",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="phase_c_voltage",
        component="fast_input",
        field="phase_c_voltage",
        translation_key="phase_c_voltage",
        legacy_name="Phase C voltage",
        requires=Capability.THREE_PHASE,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="V",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="power_factor",
        component="fast_input",
        field="power_factor",
        translation_key="power_factor",
        legacy_name="Power factor",
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=3,
    ),
    SungrowSensorDescription(
        key="power_flow_status",
        component="realtime_input",
        field="power_flow_status",
        translation_key="power_flow_status",
        legacy_name="Power Flow Status",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="reactive_power",
        component="fast_input",
        field="reactive_power",
        translation_key="reactive_power",
        legacy_name="Reactive power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="running_state_raw",
        component="realtime_input",
        field="running_state_raw",
        translation_key="running_state_raw",
        legacy_name="Running state raw",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="sungrow_arm_software",
        component="slowest_input",
        field="sungrow_arm_software",
        translation_key="sungrow_arm_software",
        legacy_name="Sungrow Arm Software",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SungrowSensorDescription(
        key="sungrow_device_type_code",
        component="slowest_input",
        field="sungrow_device_type_code",
        translation_key="sungrow_device_type_code",
        legacy_name="Sungrow device type code",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SungrowSensorDescription(
        key="sungrow_dsp_software",
        component="slowest_input",
        field="sungrow_dsp_software",
        translation_key="sungrow_dsp_software",
        legacy_name="Sungrow DSP Software",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SungrowSensorDescription(
        key="sungrow_inverter_serial",
        component="slowest_input",
        field="sungrow_inverter_serial",
        translation_key="sungrow_inverter_serial",
        legacy_name="Sungrow inverter serial",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SungrowSensorDescription(
        key="sungrow_protocol_version",
        component="slowest_input",
        field="sungrow_protocol_version",
        translation_key="sungrow_protocol_version",
        legacy_name="Sungrow Protocol Version",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SungrowSensorDescription(
        key="sungrow_version_1",
        component="slowest_input",
        field="sungrow_version_1",
        translation_key="sungrow_version_1",
        legacy_name="Sungrow Version 1",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SungrowSensorDescription(
        key="sungrow_version_2",
        component="slowest_input",
        field="sungrow_version_2",
        translation_key="sungrow_version_2",
        legacy_name="Sungrow Version 2",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SungrowSensorDescription(
        key="sungrow_version_3",
        component="slowest_input",
        field="sungrow_version_3",
        translation_key="sungrow_version_3",
        legacy_name="Sungrow Version 3",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SungrowSensorDescription(
        key="sungrow_version_4_sungrow_battery",
        component="slowest_input",
        field="sungrow_version_4_sungrow_battery",
        translation_key="sungrow_version_4_sungrow_battery",
        legacy_name="Sungrow Version 4 (Sungrow Battery)",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SungrowSensorDescription(
        key="total_active_power",
        component="fast_input",
        field="total_active_power",
        translation_key="total_active_power",
        legacy_name="Total active power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="total_backup_power",
        component="fast_input",
        field="total_backup_power",
        translation_key="total_backup_power",
        legacy_name="Total backup power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="total_battery_charge",
        component="slowest_input",
        field="total_battery_charge",
        translation_key="total_battery_charge",
        legacy_name="Total battery charge",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_battery_charge_from_pv",
        component="slowest_input",
        field="total_battery_charge_from_pv",
        translation_key="total_battery_charge_from_pv",
        legacy_name="Total battery charge from PV",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_battery_discharge",
        component="slowest_input",
        field="total_battery_discharge",
        translation_key="total_battery_discharge",
        legacy_name="Total battery discharge",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_dc_power",
        component="fast_input",
        field="total_dc_power",
        translation_key="total_dc_power",
        legacy_name="Total DC power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="W",
        suggested_display_precision=0,
    ),
    SungrowSensorDescription(
        key="total_direct_energy_consumption",
        component="slowest_input",
        field="total_direct_energy_consumption",
        translation_key="total_direct_energy_consumption",
        legacy_name="Total direct energy consumption",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_exported_energy",
        component="slowest_input",
        field="total_exported_energy",
        translation_key="total_exported_energy",
        legacy_name="Total exported energy",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_exported_energy_from_pv",
        component="slowest_input",
        field="total_exported_energy_from_pv",
        translation_key="total_exported_energy_from_pv",
        legacy_name="Total exported energy from PV",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_imported_energy",
        component="slowest_input",
        field="total_imported_energy",
        translation_key="total_imported_energy",
        legacy_name="Total imported energy",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_pv_generation",
        component="slowest_input",
        field="total_pv_generation",
        translation_key="total_pv_generation",
        legacy_name="Total PV generation",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
    SungrowSensorDescription(
        key="total_pv_generation_battery_discharge",
        component="slowest_input",
        field="total_pv_generation_battery_discharge",
        translation_key="total_pv_generation_battery_discharge",
        legacy_name="Total PV generation & battery discharge",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        native_unit_of_measurement="kWh",
        suggested_display_precision=1,
    ),
)
