#!/usr/bin/env python3
"""Record what the library reads, so the scanner can work without it.

`scripts/sungrow_scan/` is meant to be handed to a contributor as a zip: they
unpack it, run one file, and send back a document. That only works if the
scripts need nothing installed -- and two of the things they need are locked
inside `sungrow_modbus`. **Which reads** each component issues, and **how to
decode** each register.

So both are recorded here into one committed artefact, and `--check` runs in
CI, the way the nine other generators work. The scanner reads it with stdlib
`json` and is therefore exact rather than approximate: before this, the block
read test re-derived the pooling itself and, without the library, made you
type ranges by hand.

One file rather than two, deliberately. The two halves come from a single pass
over the same components, and a reader of either has to trust that they agree
about which components exist; splitting them into `block_plan.json` and
`register_map.json` would be two passes that could disagree, which is the
class of bug this artefact exists to remove.

**Derived by recording, not by reimplementing.** The blocks are whatever the
library actually asks a mock unit for, captured by wrapping its read methods
-- so the plan cannot drift from the pooling rules, the way a hand-rolled
`max_gap`/`max_span` calculation can. `scripts/sungrow_scan/blocks.py` used to
contain exactly such a calculation; it agreed with the library on this map by
luck, because nothing here uses a scale register, declares its own ranges or
repeats a group, and any of those would have broken it silently.

    python scripts/generate_scan_plan.py            # write the artefact
    python scripts/generate_scan_plan.py --check    # fail if it is stale
"""

from __future__ import annotations

import argparse
import asyncio
import json
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
# `layout.py` sits beside this file and is where the isolation lives.
sys.path.insert(0, str(Path(__file__).resolve().parent))

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "scripts" / "sungrow_scan" / "scan_plan.json"

#: Deliberately no library version in the artefact. `modbus-connection` is a
#: floating dependency, so stamping its version would fail `--check` on every
#: upstream release even when the plan is byte-identical. Provenance is this
#: file's git history.
NOTE = (
    "Generated by scripts/generate_scan_plan.py -- do not edit. Regenerate "
    "after any change to src/sungrow_modbus/registers.py or scripts/layout.py."
)


def _decimals(scale: float) -> int:
    """Return the decimal precision a scale implies.

    Copied from `modbus_connection.model.fields._decimals`, which is private
    -- and copied deliberately rather than imported, because the value is
    baked into the committed artefact where a contributor without the library
    reads it. Pinned by `tests/test_portable_decoder.py`, which decodes every
    field both ways and compares.
    """
    return max(0, len(f"{scale:.10f}".rstrip("0").split(".")[1]))


def _field_detail(name: str, resolved: object, component: str) -> dict:
    """Return everything needed to decode one register without the library."""
    field = resolved.field  # type: ignore[attr-defined]
    kind = "string" if type(field).__name__ == "StringField" else "number"
    detail: dict[str, object] = {
        "name": name,
        "component": component,
        "space": resolved.space,  # type: ignore[attr-defined]
        "address": resolved.address,  # type: ignore[attr-defined]
        "count": resolved.count,  # type: ignore[attr-defined]
        "kind": kind,
    }
    if kind == "number":
        if getattr(field, "scale_register", None) is not None:
            # Nothing in this map is dynamically scaled, and a portable
            # decoder cannot follow one: the factor comes from another
            # register read alongside. Better to stop than to publish a plan
            # whose values would be silently wrong.
            raise SystemExit(
                f"{name} is scaled by a register, which the portable decoder "
                "cannot follow. Teach it, or exclude the field."
            )
        detail |= {
            "scale": getattr(field, "scale", 1.0),
            "offset": getattr(field, "offset", 0.0),
            # Recorded rather than derived. The library rounds to the decimals
            # its scale implies, and a second implementation of that rule is a
            # second thing to keep in step -- so the number travels with the
            # field instead.
            "decimals": _decimals(getattr(field, "scale", 1.0)),
            "signed": getattr(field, "signed", False),
            "word_order": getattr(field, "word_order", "big"),
            # A field can declare several "unavailable" sentinels, so the
            # library keeps a frozenset. Sorted into a list: JSON has no set,
            # and a stable order is what keeps `--check` from flapping.
            "nan": sorted(getattr(field, "nan", None) or ()),
        }
    detail["unit"] = getattr(field, "unit", None)
    return detail


async def _record() -> tuple[list[dict], list[dict]]:
    """Drive every component against a mock unit and note what it asked for."""
    from layout import ISOLATE
    from modbus_connection.mock import MockModbusConnection

    from sungrow_modbus.battery_registers import (
        SbrBatteryCells,
        SbrBatteryModules,
        SbrBatteryPack,
    )
    from sungrow_modbus.components import InverterControl, InverterIdentity
    from sungrow_modbus.registers import COMPONENTS
    from sungrow_modbus.wallbox_registers import COMPONENTS as WALLBOX_COMPONENTS

    unit = MockModbusConnection().for_unit(1)
    seen: list[tuple[str, int, int]] = []

    def wrap(space: str, original):
        async def logged(address: int, count: int):
            seen.append((space, address, count))
            return await original(address, count)

        return logged

    unit.read_input_registers = wrap("input", unit.read_input_registers)
    unit.read_holding_registers = wrap("holding", unit.read_holding_registers)

    # The identity block is read once at setup, so the scanner needs its plan
    # too. `InverterControl` is write-only and never polled: its field is
    # listed so a bad address can still be named, but it gets no blocks.
    polled = {**COMPONENTS, "identity": InverterIdentity}

    #: Components that are **not on the inverter's unit**, and whose role
    #: says where to look for them instead.
    #:
    #: The SBR answers on unit 200 over the inverter's own LAN port and unit
    #: 2 through a WiNet-S, so the plan cannot name a number -- it names the
    #: role, and `BATTERY_PACK_UNITS` below carries the candidates to probe.
    #: Without this the survey recorded only *that* something answered at
    #: unit 200, never what it said, which is why the question of whether a
    #: dongle withholds the cell data stayed open on one path's evidence for
    #: two days.
    elsewhere = {
        "sbr_battery_pack": ("battery", SbrBatteryPack),
        "sbr_battery_cells": ("battery", SbrBatteryCells),
        "sbr_battery_modules": ("battery", SbrBatteryModules),
        # The wallbox, at unit 3 through a WiNet-S or 248 direct. Same
        # arrangement and the same reason: the plan cannot name a number, so
        # it names the role and `wallbox_units` carries the candidates.
        **{name: ("wallbox", klass) for name, klass in WALLBOX_COMPONENTS.items()},
    }
    components: list[dict] = []
    fields: list[dict] = []

    # Which components exist only because a field was moved out of its tier.
    # Recorded so the survey can tell "this needs isolating" from "this is
    # already isolated and the isolation is working" -- it printed nine
    # recommendations to add what was already there before this existed, and
    # `scripts/layout.py` is not in the zip for it to check.
    isolated = set(ISOLATE.values())

    for name, klass in polled.items():
        instance = klass(unit)
        seen.clear()
        await instance.async_update()
        components.append(
            {
                "component": name,
                "space": klass.register_space,
                "blocks": [[address, count] for _space, address, count in seen],
                **({"isolated": True} if name in isolated else {}),
            }
        )
        fields += [
            _field_detail(field_name, resolved, name)
            for field_name, resolved in instance.resolved_fields.items()
        ]

    # The battery's own components, recorded exactly the same way and marked
    # with the unit they are not on. `_field_detail` needed no teaching: it
    # already handles every scale, sentinel and word order these use.
    for name, (role, klass) in elsewhere.items():
        instance = klass(unit)
        seen.clear()
        await instance.async_update()
        components.append(
            {
                "component": name,
                "space": klass.register_space,
                "blocks": [[address, count] for _space, address, count in seen],
                "unit": role,
            }
        )
        fields += [
            _field_detail(field_name, resolved, name)
            for field_name, resolved in instance.resolved_fields.items()
        ]

    control = InverterControl(unit)
    fields += [
        _field_detail(field_name, resolved, "control")
        for field_name, resolved in control.resolved_fields.items()
    ]

    fields.sort(key=lambda entry: (entry["space"], entry["address"], entry["name"]))
    return components, fields


#: A block pair on one line. `indent=2` spreads `[5010, 25]` over five lines,
#: and the blocks are the half of this artefact a person actually reads to
#: check a plan -- so they are folded back, which also makes a diff one line
#: per changed block instead of five.
_PAIR = re.compile(r"\[\s+(\d+),\s+(\d+)\s+\]")


def derive() -> tuple[list[dict], list[dict]]:
    """Return the plan the library implies, for anyone verifying the artefact.

    Public because `scripts/sungrow_scan/blocks.py` calls it: when it happens
    to run somewhere the library is installed it checks the committed JSON
    against this and refuses to measure on a mismatch. Stale, the artefact
    would shape a measurement instead of stopping one.
    """
    return asyncio.run(_record())


def models() -> dict:
    """Return the two lookup tables that turn a reading into a name.

    Everything else in this artefact is about *getting* values; these two are
    about saying what they mean, and without them a survey run from a zip can
    read register 5000 perfectly and still only report `0x0E0E`. The summary a
    contributor pastes back would then name no model at all, and the
    document's filename -- which is derived from the model -- would be wrong
    for every device.

    Copied out of the library rather than reimplemented, so there is one
    source for the codes: `--check` fails the build when somebody adds an
    inverter to `const.DEVICE_TYPES` or a pack to `battery.MODELS` without
    regenerating.
    """
    from sungrow_modbus.battery import (
        CAPACITY_TOLERANCE_KWH,
        IDENTITY_REGISTER,
        MODELS,
        PACK_UNITS,
    )
    from sungrow_modbus.const import DEVICE_TYPES
    from sungrow_modbus.wallbox import (
        IDENTITY_LENGTH as WALLBOX_LENGTH,
        IDENTITY_REGISTER as WALLBOX_IDENTITY,
        UNITS as WALLBOX_UNITS,
    )
    from sungrow_modbus.wallbox_registers import MODELS as WALLBOX_MODELS

    return {
        # Where to look for a component the plan marks `"unit": "battery"`,
        # and how to tell a pack from a slave inverter once something
        # answers: a slave answers the device type code at this register and
        # a battery does not.
        "battery_pack_units": list(PACK_UNITS),
        "battery_identity_register": IDENTITY_REGISTER,
        # Where to look for a component the plan marks `"unit": "wallbox"`.
        # Neither number has a safe default: 3 is measured, behind a
        # WiNet-S, and 248 comes from the community projects for an
        # RS485-to-TCP adapter.
        "wallbox_units": list(WALLBOX_UNITS),
        "wallbox_identity_register": WALLBOX_IDENTITY,
        "wallbox_identity_length": WALLBOX_LENGTH,
        # Hex keys, because a device type code is hex everywhere else it
        # appears -- Sungrow's document, the model table, and the survey's own
        # output. JSON has no integer keys anyway, and "3598" beside "0x0E0E"
        # in the same file is how a wrong lookup gets written.
        "device_types": {f"0x{code:04X}": name for code, name in DEVICE_TYPES.items()},
        "battery_models": [
            {"name": model.name, "capacity_kwh": model.capacity_kwh} for model in MODELS
        ],
        # Carried with the table it applies to: a capacity match is only a
        # match inside this tolerance, and a scanner that guessed its own
        # would name an SBR096 for a 9.0 kWh third-party pack.
        "battery_capacity_tolerance_kwh": CAPACITY_TOLERANCE_KWH,
        # Which wallbox a device type code names. Two of the three come from
        # the community projects rather than from a reading here, which is
        # the point of carrying them: a contributor plugging in an AC011E-01
        # gets a named device from evidence this repository never gathered.
        "wallbox_models": {
            f"0x{code:04X}": name for code, name in WALLBOX_MODELS.items()
        },
    }


def render() -> str:
    """Return the artefact as it should be committed."""
    components, fields = derive()
    document = {
        "note": NOTE,
        "components": components,
        "fields": fields,
        **models(),
    }
    return _PAIR.sub(r"[\1, \2]", json.dumps(document, indent=2)) + "\n"


def main() -> int:
    """Write the artefact, or check the committed one is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(
                f"{OUTPUT.relative_to(REPO)} is stale.\n"
                "Run scripts/generate_scan_plan.py and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT.relative_to(REPO)} matches the library")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    document = json.loads(rendered)
    blocks = sum(len(entry["blocks"]) for entry in document["components"])
    print(
        f"Wrote {OUTPUT.relative_to(REPO)}: "
        f"{len(document['components'])} components, {blocks} blocks, "
        f"{len(document['fields'])} fields"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
